services:
  postgres:
    image: postgres:16
    container_name: shrx-erp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shrx_erp
    ports:
      - "5433:5432"
    volumes:
      - shrx_postgres_data:/var/lib/postgresql/data

volumes:
  shrx_postgres_data:
