export const SystemAccountCodes = {
  CASH: 'ASSET_CASH',
  UPI_CLEARING: 'ASSET_UPI_CLEARING',
  INVENTORY: 'ASSET_INVENTORY',
  ACCOUNTS_RECEIVABLE: 'ASSET_ACCOUNTS_RECEIVABLE',
  INPUT_CGST: 'ASSET_INPUT_CGST',
  INPUT_SGST: 'ASSET_INPUT_SGST',
  INPUT_IGST: 'ASSET_INPUT_IGST',
  COGS: 'EXPENSE_COGS',
  SALES: 'INCOME_SALES',
  ACCOUNTS_PAYABLE: 'LIABILITY_ACCOUNTS_PAYABLE',
  STORE_CREDIT: 'LIABILITY_STORE_CREDIT',
  OUTPUT_CGST: 'LIABILITY_OUTPUT_CGST',
  OUTPUT_SGST: 'LIABILITY_OUTPUT_SGST',
  OUTPUT_IGST: 'LIABILITY_OUTPUT_IGST',
  STOCK_ADJUSTMENT_EQUITY: 'EQUITY_STOCK_ADJUSTMENT'
} as const;

export const AllSystemAccountCodes = Object.values(SystemAccountCodes);
